import { StyleSheet } from 'react-native';
import colors from './colors';

const globalStyles = StyleSheet.create({
  // Containers
  container: {
    flex: 1,
    padding: 24,
    backgroundColor: '#fff',
  },
  centeredContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 20,
    backgroundColor: colors.background,
  },
  // Headers
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 24,
    marginTop: 8,
  },
  title: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#333',
  },
  subtitle: {
    color: colors.secondary,
    fontSize: 14,
    marginBottom: 10,
  },
  // Forms
  formContainer: {
    width: '100%',
    backgroundColor: colors.backgroundLight,
    borderRadius: 12,
    padding: 20,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 2,
    marginBottom: 20,
  },
  input: {
    borderWidth: 1,
    borderColor: colors.borderColor,
    borderRadius: 8,
    marginBottom: 12,
    padding: 10,
    fontSize: 16,
    backgroundColor: '#fff',
  },
  // Buttons
  primaryButton: {
    alignSelf: 'flex-start',
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 4,
    elevation: 2,
    backgroundColor: colors.primary,
  },
  secondaryButton: {
    alignSelf: 'flex-start',
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 4,
    elevation: 2,
    borderColor: colors.primary,
    backgroundColor: colors.background,
  },
  logoutButton: {
    marginTop: 20,
    marginHorizontal: 20,
    backgroundColor: colors.primary,
    borderRadius: 8,
    paddingVertical: 12,
    alignItems: 'center',
  },
  logoutText: {
    color: '#fff',
    fontWeight: '700',
    fontSize: 16,
  },
  // Footer
  footer: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 20,
    alignItems: 'center',
    justifyContent: 'center',
    paddingBottom: 0,
  },
  footerText: {
    color: colors.secondary,
    fontWeight: '600',
  },
  footerSub: {
    color: colors.mediumGray,
    fontSize: 12,
  },
  // Logo
  logo: {
    width: 150,
    height: 150,
    marginBottom: 10,
  },
  logoSmall: {
    width: 60,
    height: 60,
    marginBottom: 10,
  },
  logoContainer: {
    alignItems: 'center',
    marginBottom: 30,
  },
  // Register Link
  registerLink: {
    marginTop: 15,
    color: colors.primary,
    textAlign: 'center',
    fontWeight: '600',
    fontSize: 15,
  },
  cardWrapper: {
    flex: 1,
    minWidth: 150,
    maxWidth: 200,
    marginHorizontal: 6,
    marginBottom: 20,
    borderRadius: 16,
    backgroundColor: 'transparent',
    elevation: 6,
    shadowColor: '#000',
    shadowOpacity: 0.10,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 4 },
  },
  cardTopBorder: {
    height: 8,
    borderTopLeftRadius: 16,
    borderTopRightRadius: 16,
  },
  cardDashboard: {
    backgroundColor: '#fff',
    borderBottomLeftRadius: 16,
    borderBottomRightRadius: 16,
    borderTopLeftRadius: 0,
    borderTopRightRadius: 0,
    alignItems: 'center',
    padding: 20,
    elevation: 0,
  },
  iconContainerDashboard: {
    width: 54,
    height: 54,
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 12,
  },
  countDashboard: {
    fontSize: 32,
    fontWeight: 'bold',
    color: '#222',
    marginBottom: 4,
  },
  labelDashboard: {
    fontSize: 14,
    color: '#444B54',
    fontWeight: '500',
    textAlign: 'center',
  },
  lowStockCard: {
    backgroundColor: '#fff',
    borderRadius: 16,
    marginTop: 8,
    marginBottom: 16,
    padding: 0,
    shadowColor: '#000',
    shadowOpacity: 0.06,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 2 },
    elevation: 2,
  },
  lowStockHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 18,
    borderTopLeftRadius: 16,
    borderTopRightRadius: 16,
    backgroundColor: colors.accent,
  },
  lowStockTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    color: colors.primary,
  },
  lowStockItem: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: 'rgba(255, 87, 34, 0.04)',
    borderRadius: 14,
    borderWidth: 1,
    borderColor: colors.border,
    marginHorizontal: 18,
    marginBottom: 18,
    padding: 18,
    marginTop: 0,
  },
  lowStockProductName: {
    fontWeight: 'bold',
    fontSize: 20,
    color: colors.primary,
    marginBottom: 2,
  },
  lowStockProductInfo: {
    color: colors.secondary,
    fontSize: 15,
    marginBottom: 1,
  },
  lowStockQtdBox: {
    borderWidth: 2,
    borderColor: colors.border,
    borderRadius: 20,
    paddingHorizontal: 16,
    paddingVertical: 4,
    backgroundColor: 'rgba(255, 87, 34, 0.04)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  lowStockQtdText: {
    color: colors.secondary,
    fontWeight: 'bold',
    fontSize: 17,
  },
  osCard: {
    backgroundColor: '#fff',
    borderRadius: 16,
    marginTop: 8,
    marginBottom: 16,
    padding: 0,
    shadowColor: '#000',
    shadowOpacity: 0.06,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 2 },
    elevation: 2,
  },
  osHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 18,
    borderTopLeftRadius: 16,
    borderTopRightRadius: 16,
    backgroundColor: colors.accent,
  },
  osTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    color: colors.primary,
  },
  osItem: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: 'rgba(255, 87, 34, 0.04)',
    borderRadius: 14,
    borderWidth: 1,
    borderColor: colors.border,
    marginHorizontal: 18,
    marginBottom: 18,
    padding: 18,
    marginTop: 0,
  },
  osNumber: {
    fontWeight: 'bold',
    fontSize: 20,
    color: colors.primary,
    marginBottom: 2,
  },
  osValue: {
    color: colors.darkGreen,
    fontSize: 16,
    fontWeight: '500',
  },
  osStatusBox: {
    borderWidth: 2,
    borderColor: colors.yellowBorder,
    borderRadius: 20,
    paddingHorizontal: 16,
    paddingVertical: 4,
    backgroundColor: colors.backgroundYellow,
    alignItems: 'center',
    justifyContent: 'center',
  },
  osStatusText: {
    color: colors.darkYellow,
    fontWeight: 'bold',
    fontSize: 17,
  },
  // Report Styles
  containerReport: {
    flex: 1,
    padding: 16,
    backgroundColor: "#f5f7fa",
  },
  headerCard: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: colors.accent,
    borderRadius: 12,
    padding: 16,
    marginBottom: 16,
    justifyContent: "flex-start",
    shadowColor: "#000",
    shadowOpacity: 0.04,
    shadowRadius: 4,
    shadowOffset: { width: 0, height: 2 },
  },
  headerTitle: {
    flex: 1,
    fontSize: 22,
    fontWeight: "bold",
    color: colors.primary,
    marginLeft: 12,
  },
  card: {
    backgroundColor: "#fff",
    borderRadius: 10,
    marginBottom: 12,
    paddingVertical: 10,
    paddingHorizontal: 12,
    shadowColor: "#000",
    shadowOpacity: 0.04,
    shadowRadius: 4,
    shadowOffset: { width: 0, height: 2 },
  },
  cardRow: {
    flexDirection: "row",
    justifyContent: "flex-start",
    marginBottom: 2,
  },
  cardCell: {
    flex: 1,
    alignItems: "flex-start",
    marginVertical: 4,
  },
  cardCellFull: {
    flex: 1,
    alignItems: "flex-start",
    marginVertical: 4,
  },
  cardLabel: {
    fontWeight: "bold",
    color: "#555",
    fontSize: 13,
    marginBottom: 2,
    textAlign: "left",
  },
  cardValue: {
    color: "#222",
    fontSize: 15,
    textAlign: "left",
  },
 

});

export default globalStyles;
